### ISSUE TITLE
Error when running Cmake

### ISSUE THREAD

**Issue by YoruCathy** [jnbrunet/SofaPlaneCutting#2]
Hello, I met this error when running `cmake .`
```
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.19042.
CMake Error at CMakeLists.txt:37 (sofa_create_package):
  Unknown CMake command "sofa_create_package".


-- Configuring incomplete, errors occurred!
See also "D:/robot/food_manipulate/codes/FEM/SofaPlaneCutting-master/CMakeFiles/CMakeOutput.log".
```
My Sofa was installed by using the .exe file via download on the website. Sofa version is v21.06.00, and platform is Windows 10. 

Does anyone have some idea on how to fix this?

**Comment by YoruCathy** [comment]
I tried Ubuntu 20.04 with the same Sofa version, but the same error occurred.

**Comment by jnbrunet** [comment]
Hey @YoruCathy , I did this plugin a very long time ago for my master thesis if I remember correctly. Unfortunately, I'm running quite low on free time, and I won't be able to update this plugin anymore. However, I just looked quickly over the code and it should not be too hard for you to update it yourself if you have some basic c++ notions.
